aws:
  destination:
    host: localstack
  s3:
    bucketName: resources

database:
  expose:
    port: 5432
  image:
    name: postgres
  resources:
    requests:
      storage: 1Gi

rabbitmq:
  host: rabbitmq

service:
  expose:
    port: 8080
    api:
      health: /api/actuator/health
  image:
    name: maksimkavalenka/resource-service
    tag: 1.3.0
  deployment:
    replicas: 2
