aws:
  auth:
    access-key-id: test
    secret-access-key: test

database:
  destination:
    name: test

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

server:
  port: 8081

spring:
  datasource:
    username: test
    password: test
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    username: guest
    password: guest
    listener:
      enabled: false
