apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  {{- template "resource-service.labels" . }}
data:
  AWS_DESTINATION_HOST: {{ .Values.aws.destination.host }}.{{ .Release.Namespace }}
  AWS_S3_BUCKETNAME: {{ .Values.aws.s3.bucketName }}
  DATABASE_DESTINATION_HOST: {{ .Release.Name }}-postgres.{{ .Release.Namespace }}
  INFRASTRUCTURE_AUTHORIZATIONSERVER_HOST: {{ .Values.infrastructure.authorizationServer.host }}.{{ .Release.Namespace }}
  INFRASTRUCTURE_STORAGESERVICE_HOST: {{ .Values.infrastructure.storageService.host }}.{{ .Release.Namespace }}
  SPRING_APPLICATION_NAME: {{ .Release.Name }}
  SPRING_RABBITMQ_HOST: {{ .Values.rabbitmq.host }}.{{ .Release.Namespace }}
