apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-service-configmap
  namespace: {{ .Release.Namespace }}
  {{- template "resource-service.labels" . }}
data:
  AWS_DESTINATION_HOST: {{ .Values.aws.destination.host }}
  AWS_S3_BUCKETNAME: {{ .Values.aws.s3.bucketName }}
  DATABASE_DESTINATION_HOST: resource-service-postgres.{{ .Release.Namespace }}
  INFRASTRUCTURE_SONGSERVICE_HOST: song-service.{{ .Release.Namespace }}
  SPRING_APPLICATION_NAME: resource-service
