apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-service-configmap
  namespace: {{ .Release.Namespace }}
  {{- template "resource-service.labels" . }}
data:
  DATABASE_DESTINATION_HOST: resource-service-postgres.{{ .Release.Namespace }}
  INFRASTRUCTURE_SONGSERVICE_HOST: song-service.{{ .Release.Namespace }}
  SPRING_APPLICATION_NAME: resource-service
