apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resource-service-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1/resources$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: resource.service.com
    http:
      paths:
      - path: /(api/v1)(.*)
        pathType: Prefix
        backend:
          service:
            name: resource-service
            port:
              name: web-port
