apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resource-service-postgres-pvc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      name: microservices-learning
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.database.resources.requests.storage }}
