apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resource-service-postgres-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.database.resources.requests.storage }}
  volumeName: resource-service-postgres-pv
