apiVersion: v1
kind: Service
metadata:
  name: resource-service-postgres
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    name: resource-service-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: postgres-port

---

apiVersion: v1
kind: Service
metadata:
  name: resource-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    name: resource-service
  ports:
    - name: web-port
      protocol: TCP
      port: 8080
      targetPort: service-port
