version: '3.8'
services:
  song-service-postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${SONG_SERVICE_DATABASE_PORT}:5432"
  song-service:
    build: .
    image: maksimkavalenka/song-service:0.1.0
    restart: on-failure
    environment:
      DATABASE_PORT: ${SONG_SERVICE_DATABASE_PORT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${SONG_SERVICE_PORT}:8082"
    depends_on:
      - song-service-postgres
  resource-service-postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${RESOURCE_SERVICE_DATABASE_PORT}:5432"
  resource-service:
    build: .
    image: maksimkavalenka/resource-service:0.1.0
    restart: on-failure
    environment:
      DATABASE_PORT: ${RESOURCE_SERVICE_DATABASE_PORT}
      INFRASTRUCTURE_SONGSERVICE_PORT: ${SONG_SERVICE_PORT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${RESOURCE_SERVICE_PORT}:8081"
    depends_on:
      - resource-service-postgres
      - song-service
