apiVersion: v1
kind: PersistentVolume
metadata:
  name: microservices-learning-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
