apiVersion: v1
kind: Namespace
metadata:
  name: microservices-learning

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-service
  namespace: microservices-learning
  labels:
    name: resource-service
spec:
  replicas: 2
  selector:
    matchLabels:
      name: resource-service
  template:
    metadata:
      labels:
        name: resource-service
    spec:
      containers:
      - name: resource-service
        image: maksimkavalenka/resource-service:0.1.0
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: resource-service
spec:
  type: NodePort
  selector:
    name: resource-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
