version: '3.8'
services:
  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5401:5432"
  application:
    image: maksimkavalenka/resource-service:0.1.0
    restart: on-failure
    environment:
      DATABASE_PORT: 5401
      INFRASTRUCTURE_SONGSERVICE_PORT: 8082
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8081:8081"
    depends_on:
      - postgres
