apiVersion: v1
kind: PersistentVolume
metadata:
  name: microservices-learning-pv
  labels:
    name: microservices-learning
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
