apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-aws-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ACCESSKEYID: dGVzdA==
  SECRETACCESSKEY: dGVzdA==

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  PGUSER: cG9zdGdyZXM=
  PGPASSWORD: cG9zdGdyZXM=
  PGDATABASE: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: cG9zdGdyZXM=
