database:
  destination:
    name: test

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

server:
  port: 8082

spring:
  datasource:
    username: test
    password: test
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    username: guest
    password: guest
