version: '3.8'
services:
  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5402:5432"
  application:
    image: maksimkavalenka/song-service:0.1.0
    restart: on-failure
    environment:
      DATABASE_PORT: 5402
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8082:8082"
    depends_on:
      - postgres
