version: '3.8'
services:
  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
  application:
    build: .
    image: maksimkavalenka/song-service:0.1.0
    restart: on-failure
    environment:
      DATABASE_PORT: ${DATABASE_PORT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${APPLICATION_PORT}:8082"
    depends_on:
      - postgres
