apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.chart.name }}-configmap
  namespace: {{ .Release.Namespace }}
  {{- template "resource-processor.labels" . }}
data:
  AWS_DESTINATION_HOST: {{ .Values.aws.destination.host }}
  AWS_S3_BUCKETNAME: {{ .Values.aws.s3.bucketName }}
  INFRASTRUCTURE_SONGSERVICE_HOST: song-service.{{ .Release.Namespace }}
  SPRING_APPLICATION_NAME: {{ .Values.chart.name }}
