apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-aws-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  AWS_AUTH_ACCESSKEYID: dGVzdA==
  AWS_AUTH_SECRETACCESSKEY: dGVzdA==

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  USERNAME: YWRtaW4=
  PASSWORD: YWRtaW4=
