apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.chart.name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  AWS_AUTH_ACCESSKEYID: dGVzdA==
  AWS_AUTH_SECRETACCESSKEY: dGVzdA==
