apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  AWS_AUTH_ACCESSKEYID: dGVzdA==
  AWS_AUTH_SECRETACCESSKEY: dGVzdA==
