apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chart.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    name: {{ .Values.chart.name }}
  ports:
    - name: web-port
      protocol: TCP
      port: 8080
      targetPort: service-port
