application:
  deletion:
    limit: 200
  destination:
    host: localhost

database:
  destination:
    host: ${application.destination.host}
    port: 5432
    name: song_service
    schema: song_service

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://${eureka.destination.host}:${eureka.destination.port}/eureka/
  destination:
    host: ${application.destination.host}
    port: 8761
  instance:
    appname: ${spring.application.name}
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}

flyway:
  database:
    create-if-not-exists: true

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${application.destination.host}:9411/api/v2/spans

server:
  port: 8080
  servlet:
    contextPath: /api

spring:
  application:
    name: song-service
  datasource:
    hikari:
      schema: ${database.destination.schema}
    url: jdbc:postgresql://${database.destination.host}:${database.destination.port}/${database.destination.name}
  flyway:
    schemas: ${database.destination.schema}
    table: schema_version
  jpa:
    database: POSTGRESQL
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  servlet:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1

---

# docker

application:
  destination:
    host: host.docker.internal

spring:
  config:
    activate:
      on-profile: "docker"

---

# eureka

eureka:
  client:
    enabled: true

spring:
  config:
    activate:
      on-profile: "eureka"

---

# development

database:
  destination:
    port: 5402

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

server:
  port: 8082

spring:
  config:
    activate:
      on-profile: "development"
  datasource:
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
