loadDefinition:
  enabled: true
  existingSecret: load-definition

extraConfiguration: |
  load_definitions = /app/load_definition.json

extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "users": [
          {
            "name": "admin",
            "password_hash": "JgVoarXe+7McixkevovoCHqczEye8DDYMFcYrsSn8TFwZmSi",
            "hashing_algorithm": "rabbit_password_hashing_sha256",
            "tags": "administrator"
          }
        ],
        "vhosts": [
          {
            "name": "/"
          }
        ],
        "permissions": [
          {
            "user": "admin",
            "vhost": "/",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          }
        ],
        "queues": [
          {
            "name": "stream.resources",
            "vhost": "/",
            "durable": true,
            "auto_delete": false,
            "arguments": {
              "x-dead-letter-exchange": "topic.resources.dlq"
            }
          },
          {
            "name": "stream.resources.dlq",
            "vhost": "/",
            "durable": true,
            "auto_delete": false,
            "arguments": {
              "x-dead-letter-exchange": "topic.resources.dlq"
            }
          }
        ],
        "exchanges": [
          {
            "name": "topic.resources",
            "vhost": "/",
            "type": "topic",
            "durable": true,
            "auto_delete": false,
            "internal": false,
            "arguments": {}
          },
          {
            "name": "topic.resources.dlt",
            "vhost": "/",
            "type": "topic",
            "durable": true,
            "auto_delete": false,
            "internal": false,
            "arguments": {}
          }
        ],
        "bindings": [
          {
            "source": "topic.resources",
            "vhost": "/",
            "destination": "stream.resources",
            "destination_type": "queue",
            "routing_key": "DOMAIN.RESOURCE",
            "arguments": {}
          },
          {
            "source": "topic.resources.dlq",
            "vhost": "/",
            "destination": "stream.resources.dlq",
            "destination_type": "queue",
            "routing_key": "DOMAIN.RESOURCE.DLQ",
            "arguments": {}
          }
        ]
      }
