apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-service
  namespace: {{ .Release.Namespace }}
  labels:
    name: song-service
spec:
  replicas: {{ .Values.service.deployment.replicas }}
  selector:
    matchLabels:
      name: song-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: song-service
    spec:
      containers:
      - name: service
        image: {{ .Values.service.image.name }}:{{ .Values.service.image.tag }}
        ports:
        - name: service-port
          containerPort: {{ .Values.service.expose.port }}
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: song-service-postgres-secret
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: song-service-postgres-secret
              key: POSTGRES_PASSWORD
        envFrom:
        - configMapRef:
            name: song-service-configmap
        startupProbe:
          httpGet:
            path: {{ .Values.service.expose.api.health }}
            port: service-port
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: {{ .Values.service.expose.api.health }}
            port: service-port
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: service-port
          initialDelaySeconds: 15
          periodSeconds: 10
