apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: song-service-postgres-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.database.resources.requests.storage }}
