server:
  port : 8081
  servlet:
    contextPath: /api

spring:
  datasource:
    hikari:
      schema: resource
    url: jdbc:postgresql://localhost:5401/resource
  jpa:
    database: POSTGRESQL
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

---

spring:
  config:
    activate:
      on-profile: "development"
  datasource:
    username: admin
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
