application:
  data:
    deletion:
      limit: 200

database:
  host: localhost
  port: 5401
  name: resource_service
  schema: resource_service

flyway:
  database:
    create-if-not-exists: true

infrastructure:
  song-service:
    url: ${infrastructure.song-service.protocol}://${infrastructure.song-service.host}:${infrastructure.song-service.port}
    protocol: http
    host: localhost
    port: 8082

server:
  port : 8081
  servlet:
    contextPath: /api

spring:
  datasource:
    hikari:
      schema: ${database.schema}
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
  flyway:
    schemas: ${database.schema}
    table: schema_version
  jpa:
    database: POSTGRESQL
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  servlet:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1

---

# docker

database:
  host: host.docker.internal

infrastructure:
  song-service:
    host: host.docker.internal

spring:
  config:
    activate:
      on-profile: "docker"

---

# development

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

spring:
  config:
    activate:
      on-profile: "development"
  datasource:
    username: admin
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
