application:
  data:
    deletion:
      limit: 200

database:
  destination:
    host: localhost
    port: 5432
    name: resource_service
    schema: resource_service

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://${eureka.destination.host}:${eureka.destination.port}/eureka/
  destination:
    host: localhost
    port: 8761
  instance:
    appname: ${spring.application.name}
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}

flyway:
  database:
    create-if-not-exists: true

infrastructure:
  song-service:
    alias: song-service
    host: localhost
    port: 8080
    url: http://${infrastructure.song-service.host}:${infrastructure.song-service.port}

server:
  port: 8080
  servlet:
    contextPath: /api

spring:
  application:
    name: resource-service
  config:
    discovery:
      enabled: true
  datasource:
    hikari:
      schema: ${database.destination.schema}
    url: jdbc:postgresql://${database.destination.host}:${database.destination.port}/${database.destination.name}
  flyway:
    schemas: ${database.destination.schema}
    table: schema_version
  jpa:
    database: POSTGRESQL
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  servlet:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1

---

# docker

docker:
  destination:
    host: host.docker.internal

database:
  destination:
    host: ${docker.destination.host}

eureka:
  destination:
    host: ${docker.destination.host}

spring:
  config:
    activate:
      on-profile: "docker"

---

# eureka

eureka:
  client:
    enabled: true

infrastructure:
  song-service:
    url: ""

spring:
  config:
    activate:
      on-profile: "eureka"

---

# development

database:
  destination:
    port: 5401

infrastructure:
  song-service:
    port: 8082

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

server:
  port: 8081

spring:
  config:
    activate:
      on-profile: "development"
  datasource:
    username: admin
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
