aws:
  destination:
    host: localstack
  s3:
    bucketName: resources

infrastructure:
  songService:
    host: song-service

rabbitmq:
  host: rabbitmq

service:
  expose:
    port: 8080
    api:
      health: /api/actuator/health
  image:
    name: maksimkavalenka/microservices-learning.resource-processor
    tag: latest
  deployment:
    replicas: 2
