aws:
  destination:
    host: localstack
  s3:
    bucketName: resources

chart:
  name: resource-processor

service:
  expose:
    port: 8080
    api:
      health: /api/actuator/health
  image:
    name: maksimkavalenka/resource-processor
    tag: 1.0.0
  deployment:
    replicas: 2
